//----------------------
// <auto-generated>
//	Generated by the BindableViewModelMappingGenerator v1. DO NOT EDIT!
//	Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//----------------------
#pragma warning disable

namespace ImmutableEditableObjectAdapter.Samples.Uno
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("BindableViewModelMappingGenerator", "1")]
	public static partial class ReactiveViewModelMappings
	{
		/// <summary>
		/// Gets a mapping from a declared view model type (key) to its bindable counterpart type (value) generated by the feeds platform.
		/// </summary>
		/// <remarks>
		/// This can be used in navigation engine to work only with the declared type while the navigation takes care to use the bindable friendly version.
		/// </remarks>
		public static readonly global::System.Collections.Generic.IDictionary<global::System.Type, global::System.Type> ViewModelMappings = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Type>
		{
			{ typeof(ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainModel), typeof(global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainViewModel) },
			{ typeof(ImmutableEditableObjectAdapter.Samples.Uno.Presentation.SecondModel), typeof(global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.SecondViewModel) },
		};
	}
}