//----------------------
	// <auto-generated>
	//	Generated by the ViewModelGenerator_2 v2. DO NOT EDIT!
	//	Manual changes to this file will be overwritten if the code is regenerated.
	// </auto-generated>
	//----------------------
	#pragma warning disable

using System;
using System.Linq;
using System.Threading.Tasks;

namespace ImmutableEditableObjectAdapter.Samples.Uno.Models
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ViewModelGenerator_2", "2")]
	public sealed class BindablePersonViewModel : global::Uno.Extensions.Reactive.Bindings.Bindable<ImmutableEditableObjectAdapter.Samples.Uno.Models.Person>
	{
		private readonly global::Uno.Extensions.Reactive.Bindings.Bindable<string> _name;
		private readonly global::Uno.Extensions.Reactive.Bindings.Bindable<string> _favouriteColor;
		private readonly global::Uno.Extensions.Reactive.Bindings.Bindable<global::System.DateTimeOffset> _birthDay;
		private readonly global::Uno.Extensions.Reactive.Bindings.Bindable<global::System.DateTimeOffset?> _deceasedAt;

		public BindablePersonViewModel(global::Uno.Extensions.Reactive.Bindings.BindablePropertyInfo<ImmutableEditableObjectAdapter.Samples.Uno.Models.Person> property)
			: base(property, hasValueProperty: true)
		{
			_name = new global::Uno.Extensions.Reactive.Bindings.Bindable<string>(base.Property<string>(
				nameof(Name),
				person => person?.Name ?? default(string),
				(person, name) => (person ?? CreateDefault()) with {Name = name}));
			_favouriteColor = new global::Uno.Extensions.Reactive.Bindings.Bindable<string>(base.Property<string>(
				nameof(FavouriteColor),
				person => person?.FavouriteColor ?? default(string),
				(person, favouriteColor) => (person ?? CreateDefault()) with {FavouriteColor = favouriteColor}));
			_birthDay = new global::Uno.Extensions.Reactive.Bindings.Bindable<global::System.DateTimeOffset>(base.Property<global::System.DateTimeOffset>(
				nameof(BirthDay),
				person => person?.BirthDay ?? default(global::System.DateTimeOffset),
				(person, birthDay) => (person ?? CreateDefault()) with {BirthDay = birthDay}));
			_deceasedAt = new global::Uno.Extensions.Reactive.Bindings.Bindable<global::System.DateTimeOffset?>(base.Property<global::System.DateTimeOffset?>(
				nameof(DeceasedAt),
				person => person?.DeceasedAt ?? default(global::System.DateTimeOffset?),
				(person, deceasedAt) => (person ?? CreateDefault()) with {DeceasedAt = deceasedAt}));
		}

		private static ImmutableEditableObjectAdapter.Samples.Uno.Models.Person CreateDefault()
			=> new(default(string)!, default(string)!, default(global::System.DateTimeOffset)!, default(global::System.DateTimeOffset?)!);

		public global::ImmutableEditableObjectAdapter.Samples.Uno.Models.Person Value
{
	get => base.GetValue();
	set => base.SetValue(value);
}


		public string Name
		{
			get => _name.GetValue();
			set => _name.SetValue(value);
		}

		public string FavouriteColor
		{
			get => _favouriteColor.GetValue();
			set => _favouriteColor.SetValue(value);
		}

		public global::System.DateTimeOffset BirthDay
		{
			get => _birthDay.GetValue();
			set => _birthDay.SetValue(value);
		}

		public global::System.DateTimeOffset? DeceasedAt
		{
			get => _deceasedAt.GetValue();
			set => _deceasedAt.SetValue(value);
		}

	}
}
