//----------------------
			// <auto-generated>
			//	Generated by the ViewModelGenTool_3 v3. DO NOT EDIT!
			//	Manual changes to this file will be overwritten if the code is regenerated.
			// </auto-generated>
			//----------------------
			#pragma warning disable

			namespace ImmutableEditableObjectAdapter.Samples.Uno.Presentation
			{
				[global::Uno.Extensions.Reactive.Bindings.Model(typeof(global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainViewModel))]
[global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdate]
partial record MainModel : global::System.IAsyncDisposable, global::Uno.Extensions.Reactive.Core.ISourceContextAware, global::Uno.Extensions.Reactive.Bindings.IModel<global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainViewModel>
				{

					[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
					internal global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainViewModel __reactiveBindableViewModel = default!;

					/// <inheritdoc />
					global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainViewModel global::Uno.Extensions.Reactive.Bindings.IModel<global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainViewModel>.ViewModel => __reactiveBindableViewModel;

					/// <inheritdoc />
					[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ViewModelGenTool_3", "3")]
					public global::System.Threading.Tasks.ValueTask DisposeAsync()
						=> global::Uno.Extensions.Reactive.Core.SourceContext.Find(this)?.DisposeAsync() ?? default;

				}
			}