//----------------------
				// <auto-generated>
				//	Generated by the UIModuleInitializerGenerator v1. DO NOT EDIT!
				//	Manual changes to this file will be overwritten if the code is regenerated.
				// </auto-generated>
				//----------------------
				#pragma warning disable

namespace ImmutableEditableObjectAdapter.Samples.Uno
{
	/// <summary>
	/// Initialize provider of dispatcher.
	/// </summary>
	/// <remarks>This class ensures that dispatcher has been initialized even if the Reactive.UI package has not been loaded yet.</remarks>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("UIModuleInitializerGenerator", "1")]
	internal static class __ReactiveUIModuleInitializer
	{
		/// <summary>
		/// Register the <seealso cref="DispatcherQueueProvider"/> as provider of <see cref="IDispatcher"/> for the reactive platform.
		/// </summary>
		/// <remarks>This method is flagged with ModuleInitializer attribute and should not be used by application.</remarks>
		[global::System.Runtime.CompilerServices.ModuleInitializer]
		public static void Initialize()
		{
			global::Uno.Extensions.Reactive.UI.ModuleInitializer.Initialize();
		}
	}
}
