// <auto-generated>
// *******************************************************************
// This file has been generated by Uno.UI.HotDesign.SourceGenerators
// *******************************************************************
// </auto-generated>
// <autogenerated />

[assembly: global::Uno.UI.HotDesign.Client.ServerProcessorPathAttribute("C:\\Users\\rca\\.nuget\\packages\\uno.ui.hotdesign\\1.11.182\\lib\\net8.0\\..\\..\\tools\\net8.0\\server\\Uno.UI.HotDesign.Server.dll")]
