//----------------------
				// <auto-generated>
				//	Generated by the HotReloadModuleInitializerGenerator v1. DO NOT EDIT!
				//	Manual changes to this file will be overwritten if the code is regenerated.
				// </auto-generated>
				//----------------------
				#pragma warning disable

namespace ImmutableEditableObjectAdapter.Samples.Uno
{
	/// <summary>
	/// Initialize hot-reload support.
	/// </summary>
	/// <remarks>This class ensures that the hot-reload support is enabled only when needed (i.e. !IS_HOT_RELOAD_DISABLED && (DEBUG || IS_HOT_RELOAD_ENABLED).</remarks>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("HotReloadModuleInitializerGenerator", "1")]
	internal static class __ReactiveHotReloadModuleInitializer
	{
		/// <summary>
		/// Configures hot-reload for MVUX.
		/// </summary>
		/// <remarks>This method is flagged with ModuleInitializer attribute and should not be used by application.</remarks>
		[global::System.Runtime.CompilerServices.ModuleInitializer]
		public static void Initialize()
		{
#if !IS_HOT_RELOAD_DISABLED && (DEBUG || IS_HOT_RELOAD_ENABLED)
			var isEnabled = true;
#else
			var isEnabled = false;
#endif
			global::Uno.Extensions.Reactive.Config.ModuleFeedConfiguration.ConfigureHotReload("ImmutableEditableObjectAdapter.Samples.Uno", isEnabled);
		}
	}
}
