// <autogenerated />
#pragma warning disable 618 // Ignore obsolete members warnings
#pragma warning disable 105 // Ignore duplicate namespaces
#pragma warning disable 1591 // Ignore missing XML comment warnings
#pragma warning disable CS8669 // Ignore annotation for nullable reference types
#pragma warning disable CS9113 // Parameter is unread
#pragma warning disable CS0114
#pragma warning disable CS0108
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Uno.UI;
using Uno.UI.Xaml;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Documents;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Media.Animation;
using Microsoft.UI.Xaml.Shapes;
using Windows.UI.Text;
using Uno.Extensions;
using Uno;
using Uno.UI.Helpers;
using Uno.UI.Helpers.Xaml;
using ImmutableEditableObjectAdapter.Samples.Uno;

#if HAS_UNO_SKIA
using _View = Microsoft.UI.Xaml.UIElement;
#elif __ANDROID__
using _View = Android.Views.View;
#elif __APPLE_UIKIT__ || __IOS__ || __TVOS__
using _View = UIKit.UIView;
#else
using _View = Microsoft.UI.Xaml.UIElement;
#endif

namespace ImmutableEditableObjectAdapter.Samples.Uno
{
	partial class App : global::Microsoft.UI.Xaml.Application
	{
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private const string __baseUri_prefix_App_92fe2aed9105f6632fee946d52fcfbc5 = "ms-appx:///";
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private const string __baseUri_App_92fe2aed9105f6632fee946d52fcfbc5 = "ms-appx:///App.xaml";
		private global::Microsoft.UI.Xaml.NameScope __nameScope = new global::Microsoft.UI.Xaml.NameScope();
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void InitializeComponent()
		{
			var __that = this;
			global::Uno.UI.RemoteControl.RemoteControlClient.Initialize(GetType());
			global::Uno.Foundation.Extensibility.ApiExtensibility.Register(typeof(global::Microsoft.UI.Xaml.Controls.ILottieVisualSourceProvider), o => new global::Uno.UI.Lottie.LottieVisualSourceProvider(o));
			global::Windows.ApplicationModel.Resources.ResourceLoader.DefaultLanguage = "en";
			global::Windows.ApplicationModel.Resources.ResourceLoader.AddLookupAssembly(GetType().Assembly);
			global::Windows.ApplicationModel.Resources.ResourceLoader.AddLookupAssembly(global::System.Reflection.Assembly.Load("Microsoft.Xaml.Interactions"));
			global::Windows.ApplicationModel.Resources.ResourceLoader.AddLookupAssembly(global::System.Reflection.Assembly.Load("Uno.UI"));
			global::Windows.ApplicationModel.Resources.ResourceLoader.AddLookupAssembly(global::System.Reflection.Assembly.Load("Uno.UI.HotDesign.Xaml.Interactions"));
			global::Windows.ApplicationModel.Resources.ResourceLoader.AddLookupAssembly(global::System.Reflection.Assembly.Load("Uno.UI.HotDesign.Xaml.Interactivity"));

			this
			.GenericApply(__that, __nameScope, (ApplyMethod_0))
			;

			global::ImmutableEditableObjectAdapter.Samples.Uno.GlobalStaticResources.Initialize();
			global::ImmutableEditableObjectAdapter.Samples.Uno.GlobalStaticResources.RegisterResourceDictionariesBySourceLocal();
			global::Uno.UI.DataBinding.BindableMetadata.Provider = new global::ImmutableEditableObjectAdapter.Samples.Uno.BindableMetadataProvider();
			// MergedDictionaries
			Resources.MergedDictionaries.Add(
			new global::Microsoft.UI.Xaml.Controls.XamlControlsResourcesV2()
			{
			}
			);
			Resources.MergedDictionaries.Add(
			new /* typed resource dictionary */ global::Uno.Toolkit.UI.Material.MaterialToolkitTheme()
			{
				ColorOverrideSource = "ms-appx:///Styles/ColorPaletteOverride.xaml",
			}
			);
			// Source ..\..\..\App.xaml (Line 1:2)
			global::Uno.UI.FeatureConfiguration.Font.SymbolsFont = "ms-appx:///Uno.Fonts.Fluent/Fonts/uno-fluentui-assets.ttf";
#if DEBUG && !DISABLE_GENERATED_UNHANDLED_EXCEPTION_HANDLER
			UnhandledException += (s, e) =>
			{
				if (global::System.Diagnostics.Debugger.IsAttached)
				{
					global::System.Diagnostics.Debug.WriteLine(e.Exception);
#if !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
					global::System.Diagnostics.Debugger.Break();
#endif
				}
			};
#endif
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_0(global::Microsoft.UI.Xaml.Application __p1, App __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			// Source ..\..\..\App.xaml (Line 1:2)
			
			// WARNING Property __p1.base does not exist on {http://schemas.microsoft.com/winfx/2006/xaml/presentation}Application, the namespace is http://www.w3.org/XML/1998/namespace. This error was considered irrelevant by the XamlFileGenerator
		}
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		[global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdate]
		private class __App_92fe2aed9105f6632fee946d52fcfbc5_ImmutableEditableObjectAdapterSamplesUnoApp
		{
		}
		private interface IApp_Bindings
		{
			void Initialize();
			void Update();
			void UpdateResources();
			void StopTracking();
			void NotifyXLoad(string name);
		}
		#pragma warning disable 0169 //  Suppress unused field warning in case Bindings is not used.
		private IApp_Bindings Bindings;
		#pragma warning restore 0169
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		private class App_Bindings : IApp_Bindings
		{
			#if UNO_HAS_UIELEMENT_IMPLICIT_PINNING
			private global::System.WeakReference _ownerReference;
			private global::ImmutableEditableObjectAdapter.Samples.Uno.App Owner { get => (global::ImmutableEditableObjectAdapter.Samples.Uno.App)_ownerReference?.Target; set => _ownerReference = new global::System.WeakReference(value); }
			#else
			private global::ImmutableEditableObjectAdapter.Samples.Uno.App Owner { get; set; }
			#endif
			public App_Bindings(global::ImmutableEditableObjectAdapter.Samples.Uno.App owner)
			{
				Owner = owner;
			}
			void IApp_Bindings.NotifyXLoad(string name)
			{
			}
			void IApp_Bindings.Initialize()
			{
			}
			void IApp_Bindings.Update()
			{
				var owner = Owner;
			}
			void IApp_Bindings.UpdateResources()
			{
				var owner = Owner;
			}
			void IApp_Bindings.StopTracking()
			{
				var owner = Owner;
			}
		}
	}
}
