// <autogenerated />
#pragma warning disable 618 // Ignore obsolete members warnings
#pragma warning disable 105 // Ignore duplicate namespaces
#pragma warning disable 1591 // Ignore missing XML comment warnings
#pragma warning disable CS8669 // Ignore annotation for nullable reference types
#pragma warning disable CS9113 // Parameter is unread
namespace ImmutableEditableObjectAdapter.Samples.Uno
{
	/// <summary>
	/// Contains all the static resources defined for the application
	/// </summary>
	[global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdate]
	public sealed partial class GlobalStaticResources
	{
		static bool _initialized;
		private static bool _stylesRegistered;
		private static bool _dictionariesRegistered;
		internal static global::Uno.UI.Xaml.XamlParseContext __ParseContext_ { get; } = new global::Uno.UI.Xaml.XamlParseContext()
		{
			AssemblyName = "ImmutableEditableObjectAdapter.Samples.Uno",
		}
		;

		static GlobalStaticResources()
		{
			Initialize();
		}
		public static void Initialize()
		{
			if (!_initialized)
			{
				_initialized = true;
				global::CommunityToolkit.WinUI.GlobalStaticResources.Initialize();
				global::CommunityToolkit.WinUI.UI.Controls.DG.GlobalStaticResources.Initialize();
				global::CommunityToolkit.WinUI.UI.GlobalStaticResources.Initialize();
				global::Microsoft.Xaml.Interactions.GlobalStaticResources.Initialize();
				global::Microsoft.Xaml.Interactivity.GlobalStaticResources.Initialize();
				global::SkiaSharp.Views.Windows.GlobalStaticResources.Initialize();
				global::Uno.Extensions.GlobalStaticResources.Initialize();
				global::Uno.Extensions.Hosting.WinUI.GlobalStaticResources.Initialize();
				global::Uno.Extensions.Localization.WinUI.GlobalStaticResources.Initialize();
				global::Uno.Extensions.Logging.WinUI.GlobalStaticResources.Initialize();
				global::Uno.Extensions.Navigation.Toolkit.WinUI.GlobalStaticResources.Initialize();
				global::Uno.Extensions.Navigation.WinUI.GlobalStaticResources.Initialize();
				global::Uno.Extensions.Reactive.WinUI.GlobalStaticResources.Initialize();
				global::Uno.Extensions.Storage.WinUI.GlobalStaticResources.Initialize();
				global::Uno.Material.WinUI.GlobalStaticResources.Initialize();
				global::Uno.Themes.WinUI.GlobalStaticResources.Initialize();
				global::Uno.Toolkit.UI.GlobalStaticResources.Initialize();
				global::Uno.Toolkit.UI.Material.GlobalStaticResources.Initialize();
				global::Uno.UI.GlobalStaticResources.Initialize();
				global::Uno.UI.HotDesign.Client.Core.GlobalStaticResources.Initialize();
				global::Uno.UI.HotDesign.Client.GlobalStaticResources.Initialize();
				global::Uno.UI.HotDesign.CommunityToolkit.GlobalStaticResources.Initialize();
				global::Uno.UI.HotDesign.GlobalStaticResources.Initialize();
				global::Uno.UI.HotDesign.Hierarchy.GlobalStaticResources.Initialize();
				global::Uno.UI.HotDesign.PropertyGrid.GlobalStaticResources.Initialize();
				global::Uno.UI.HotDesign.Toolbox.GlobalStaticResources.Initialize();
				global::Uno.UI.HotDesign.Xaml.Interactions.GlobalStaticResources.Initialize();
				global::Uno.UI.HotDesign.Xaml.Interactivity.GlobalStaticResources.Initialize();
				global::Uno.UI.Lottie.GlobalStaticResources.Initialize();
				global::Uno.UI.RemoteControl.GlobalStaticResources.Initialize();
				global::Uno.UI.Toolkit.GlobalStaticResources.Initialize();
				global::CommunityToolkit.WinUI.GlobalStaticResources.RegisterDefaultStyles();
				global::CommunityToolkit.WinUI.UI.Controls.DG.GlobalStaticResources.RegisterDefaultStyles();
				global::CommunityToolkit.WinUI.UI.GlobalStaticResources.RegisterDefaultStyles();
				global::Microsoft.Xaml.Interactions.GlobalStaticResources.RegisterDefaultStyles();
				global::Microsoft.Xaml.Interactivity.GlobalStaticResources.RegisterDefaultStyles();
				global::SkiaSharp.Views.Windows.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Extensions.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Extensions.Hosting.WinUI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Extensions.Localization.WinUI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Extensions.Logging.WinUI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Extensions.Navigation.Toolkit.WinUI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Extensions.Navigation.WinUI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Extensions.Reactive.WinUI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Extensions.Storage.WinUI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Material.WinUI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Themes.WinUI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Toolkit.UI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.Toolkit.UI.Material.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.HotDesign.Client.Core.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.HotDesign.Client.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.HotDesign.CommunityToolkit.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.HotDesign.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.HotDesign.Hierarchy.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.HotDesign.PropertyGrid.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.HotDesign.Toolbox.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.HotDesign.Xaml.Interactions.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.HotDesign.Xaml.Interactivity.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.Lottie.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.RemoteControl.GlobalStaticResources.RegisterDefaultStyles();
				global::Uno.UI.Toolkit.GlobalStaticResources.RegisterDefaultStyles();
				global::CommunityToolkit.WinUI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::CommunityToolkit.WinUI.UI.Controls.DG.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::CommunityToolkit.WinUI.UI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Microsoft.Xaml.Interactions.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Microsoft.Xaml.Interactivity.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::SkiaSharp.Views.Windows.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Extensions.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Extensions.Hosting.WinUI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Extensions.Localization.WinUI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Extensions.Logging.WinUI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Extensions.Navigation.Toolkit.WinUI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Extensions.Navigation.WinUI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Extensions.Reactive.WinUI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Extensions.Storage.WinUI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Material.WinUI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Themes.WinUI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Toolkit.UI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.Toolkit.UI.Material.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.HotDesign.Client.Core.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.HotDesign.Client.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.HotDesign.CommunityToolkit.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.HotDesign.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.HotDesign.Hierarchy.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.HotDesign.PropertyGrid.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.HotDesign.Toolbox.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.HotDesign.Xaml.Interactions.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.HotDesign.Xaml.Interactivity.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.Lottie.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.RemoteControl.GlobalStaticResources.RegisterResourceDictionariesBySource();
				global::Uno.UI.Toolkit.GlobalStaticResources.RegisterResourceDictionariesBySource();
			}
		}
		public static void RegisterDefaultStyles()
		{
			if(!_stylesRegistered)
			{
				_stylesRegistered = true;
				RegisterDefaultStyles_App_92fe2aed9105f6632fee946d52fcfbc5();
				RegisterDefaultStyles_ColorPaletteOverride_6acd3e31fd1cf74bad6fe8ae493e7985();
				RegisterDefaultStyles_MainPage_d7a1b33751a06f8c2b641494e8c25f72();
				RegisterDefaultStyles_SecondPage_43d52a7b8ef7245df955f57a30f3e88c();
				RegisterDefaultStyles_Shell_06fa6f052ecac338a77d04463cc3e67a();
			}
		}
		// Register ResourceDictionaries using ms-appx:/// syntax, this is called for external resources
		public static void RegisterResourceDictionariesBySource()
		{
			if(!_dictionariesRegistered)
			{
				_dictionariesRegistered = true;
				global::Uno.UI.ResourceResolver.RegisterResourceDictionaryBySource(uri: "ms-appx:///ImmutableEditableObjectAdapter.Samples.Uno/Styles/ColorPaletteOverride.xaml", context: __ParseContext_, dictionary: () => ColorPaletteOverride_6acd3e31fd1cf74bad6fe8ae493e7985_ResourceDictionary);
			}
		}
		// Register ResourceDictionaries using ms-resource:/// syntax, this is called for local resources
		internal static void RegisterResourceDictionariesBySourceLocal()
		{
			global::Uno.UI.ResourceResolver.RegisterResourceDictionaryBySource(uri: "ms-resource:///Files/Styles/ColorPaletteOverride.xaml", context: null, dictionary: () => ColorPaletteOverride_6acd3e31fd1cf74bad6fe8ae493e7985_ResourceDictionary, "C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Styles/ColorPaletteOverride.xaml");
			global::Uno.UI.ResourceResolver.RegisterResourceDictionaryBySource(uri: "ms-appx:///Styles/ColorPaletteOverride.xaml", context: null, dictionary: () => ColorPaletteOverride_6acd3e31fd1cf74bad6fe8ae493e7985_ResourceDictionary);
		}
		static partial void RegisterDefaultStyles_App_92fe2aed9105f6632fee946d52fcfbc5();
		static partial void RegisterDefaultStyles_ColorPaletteOverride_6acd3e31fd1cf74bad6fe8ae493e7985();
		static partial void RegisterDefaultStyles_MainPage_d7a1b33751a06f8c2b641494e8c25f72();
		static partial void RegisterDefaultStyles_SecondPage_43d52a7b8ef7245df955f57a30f3e88c();
		static partial void RegisterDefaultStyles_Shell_06fa6f052ecac338a77d04463cc3e67a();
		
	}
}
