// <autogenerated />
#pragma warning disable 618 // Ignore obsolete members warnings
#pragma warning disable 105 // Ignore duplicate namespaces
#pragma warning disable 1591 // Ignore missing XML comment warnings
#pragma warning disable CS8669 // Ignore annotation for nullable reference types
#pragma warning disable CS9113 // Parameter is unread
#pragma warning disable CS0114
#pragma warning disable CS0108
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Uno.UI;
using Uno.UI.Xaml;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Documents;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Media.Animation;
using Microsoft.UI.Xaml.Shapes;
using Windows.UI.Text;
using Uno.Extensions;
using Uno;
using Uno.UI.Helpers;
using Uno.UI.Helpers.Xaml;
using ImmutableEditableObjectAdapter.Samples.Uno;

#if HAS_UNO_SKIA
using _View = Microsoft.UI.Xaml.UIElement;
#elif __ANDROID__
using _View = Android.Views.View;
#elif __APPLE_UIKIT__ || __IOS__ || __TVOS__
using _View = UIKit.UIView;
#else
using _View = Microsoft.UI.Xaml.UIElement;
#endif

namespace ImmutableEditableObjectAdapter.Samples.Uno.Presentation
{
	partial class MainPage : global::Microsoft.UI.Xaml.Controls.Page
	{
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private const string __baseUri_prefix_MainPage_d7a1b33751a06f8c2b641494e8c25f72 = "ms-appx:///";
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private const string __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72 = "ms-appx:///Presentation/MainPage.xaml";
		private global::Microsoft.UI.Xaml.NameScope __nameScope = new global::Microsoft.UI.Xaml.NameScope();
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void InitializeComponent()
		{
			NameScope.SetNameScope(this, __nameScope);
			var __that = this;
			base.IsParsing = true;
			Resources[
			"EditablePersonValueConverter"
			] = 
			new global::ImmutableEditableObjectAdapter.Samples.Uno.Converters.EditablePersonValueConverter
			{
				// Source ..\..\..\Presentation\MainPage.xaml (Line 16:6)
			}
			;
			// Source ..\..\..\Presentation\MainPage.xaml (Line 1:2)
			base.Content = 
			new global::Microsoft.UI.Xaml.Controls.ScrollViewer
			{
				IsParsing = true,
				IsTabStop = true,
				// Source ..\..\..\Presentation\MainPage.xaml (Line 18:4)
				Content = 
				new global::Microsoft.UI.Xaml.Controls.Grid
				{
					IsParsing = true,
					RowDefinitions = 
					{
						new global::Microsoft.UI.Xaml.Controls.RowDefinition
						{
							Height = new global::Microsoft.UI.Xaml.GridLength(1f, global::Microsoft.UI.Xaml.GridUnitType.Auto),
							// Source ..\..\..\Presentation\MainPage.xaml (Line 21:10)
						}
						,
						new global::Microsoft.UI.Xaml.Controls.RowDefinition
						{
							// Source ..\..\..\Presentation\MainPage.xaml (Line 22:10)
						}
						,
					}
					,
					// Source ..\..\..\Presentation\MainPage.xaml (Line 19:6)
					Children = 
					{
						new global::Uno.Toolkit.UI.NavigationBar
						{
							IsParsing = true,
							// Source ..\..\..\Presentation\MainPage.xaml (Line 24:8)
						}
						.GenericApply(__that, __nameScope, (ApplyMethod_1))
						,
						new global::Microsoft.UI.Xaml.Controls.StackPanel
						{
							IsParsing = true,
							HorizontalAlignment = global::Microsoft.UI.Xaml.HorizontalAlignment.Center,
							VerticalAlignment = global::Microsoft.UI.Xaml.VerticalAlignment.Center,
							Spacing = 16d,
							// Source ..\..\..\Presentation\MainPage.xaml (Line 26:8)
							Children = 
							{
								new global::Microsoft.UI.Xaml.Controls.TextBox
								{
									IsParsing = true,
									PlaceholderText = "Enter your name:",
									// Source ..\..\..\Presentation\MainPage.xaml (Line 30:10)
								}
								.GenericApply(__that, __nameScope, (ApplyMethod_2))
								,
								new global::Microsoft.UI.Xaml.Controls.Button
								{
									IsParsing = true,
									Content = @"Go to Second Page",
									// Source ..\..\..\Presentation\MainPage.xaml (Line 32:10)
								}
								.GenericApply(__that, __nameScope, (ApplyMethod_3))
								,
								new global::Microsoft.UI.Xaml.Controls.TextBox
								{
									IsParsing = true,
									IsReadOnly = true,
									Header = @"Changed Name",
									// Source ..\..\..\Presentation\MainPage.xaml (Line 36:10)
								}
								.GenericApply(__that, __nameScope, (ApplyMethod_4))
								,
								new global::Microsoft.UI.Xaml.Controls.TextBox
								{
									IsParsing = true,
									IsReadOnly = true,
									Header = @"Changed Favourite Colour",
									// Source ..\..\..\Presentation\MainPage.xaml (Line 37:10)
								}
								.GenericApply(__that, __nameScope, (ApplyMethod_5))
								,
								new global::Uno.Extensions.Reactive.UI.FeedView
								{
									IsParsing = true,
									ValueTemplate = 									new global::Microsoft.UI.Xaml.DataTemplate(this, (__owner) => 									new __MainPage_d7a1b33751a06f8c2b641494e8c25f72_ImmutableEditableObjectAdapterSamplesUnoPresentationMainPage.SC0().Build(__owner)
									)									.GenericApply(__that, __nameScope, (ApplyMethod_6))
									,
									// Source ..\..\..\Presentation\MainPage.xaml (Line 39:10)
								}
								.GenericApply(__that, __nameScope, (ApplyMethod_7))
								,
							}
						}
						.GenericApply(__that, __nameScope, (ApplyMethod_8))
						,
					}
				}
				.GenericApply(__that, __nameScope, (ApplyMethod_9))
				,
			}
			.GenericApply(__that, __nameScope, (ApplyMethod_10))
			;
			
			this
			.GenericApply(__that, __nameScope, (ApplyMethod_11))
			.GenericApply(__that, __nameScope, (ApplyMethod_12))
			;
			OnInitializeCompleted();

			Bindings = new MainPage_Bindings(this);
			((global::Microsoft.UI.Xaml.FrameworkElement)this).Loading += __UpdateBindingsAndResources;
		}
		partial void OnInitializeCompleted();
		private void __UpdateBindingsAndResources(global::Microsoft.UI.Xaml.FrameworkElement s, object e)
		{
			this.Bindings.UpdateResources();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_1(global::Uno.Toolkit.UI.NavigationBar __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			__p1.SetBinding(
				global::Uno.Toolkit.UI.NavigationBar.ContentProperty,
				new Microsoft.UI.Xaml.Data.Binding()
				{
					Path = @"Title",
				}
			);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 24, 8);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_2(global::Microsoft.UI.Xaml.Controls.TextBox __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			__p1.SetBinding(
				global::Microsoft.UI.Xaml.Controls.TextBox.TextProperty,
				new Microsoft.UI.Xaml.Data.Binding()
				{
					Path = @"Name",
					Mode = global::Microsoft.UI.Xaml.Data.BindingMode.TwoWay,
				}
			);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 30, 10);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_3(global::Microsoft.UI.Xaml.Controls.Button __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			global::Microsoft.UI.Xaml.Automation.AutomationProperties.SetAutomationId(__p1, "SecondPageButton");
			__p1.SetBinding(
				global::Microsoft.UI.Xaml.Controls.Button.CommandProperty,
				new Microsoft.UI.Xaml.Data.Binding()
				{
					Path = @"GoToSecond",
				}
			);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 32, 10);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_4(global::Microsoft.UI.Xaml.Controls.TextBox __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			__p1.SetBinding(
				global::Microsoft.UI.Xaml.Controls.TextBox.TextProperty,
				new Microsoft.UI.Xaml.Data.Binding()
				{
					Path = @"LastEdited.Name",
				}
			);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 36, 10);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_5(global::Microsoft.UI.Xaml.Controls.TextBox __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			__p1.SetBinding(
				global::Microsoft.UI.Xaml.Controls.TextBox.TextProperty,
				new Microsoft.UI.Xaml.Data.Binding()
				{
					Path = @"LastEdited.FavouriteColor",
				}
			);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 37, 10);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_6(global::System.Object __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			global::Uno.UI.Helpers.MarkupHelper.SetElementProperty(__p1, "OriginalSourceLocation", "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml#L41:14");
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_7(global::Uno.Extensions.Reactive.UI.FeedView __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			__p1.SetBinding(
				global::Uno.Extensions.Reactive.UI.FeedView.SourceProperty,
				new Microsoft.UI.Xaml.Data.Binding()
				{
					Path = @"Persons",
					Converter = (global::Microsoft.UI.Xaml.Data.IValueConverter)global::Uno.UI.ResourceResolverSingleton.Instance.ResolveResourceStatic("EditablePersonValueConverter", typeof(global::Microsoft.UI.Xaml.Data.IValueConverter), context: global::ImmutableEditableObjectAdapter.Samples.Uno.GlobalStaticResources.__ParseContext_),
				}
			);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 39, 10);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_8(global::Microsoft.UI.Xaml.Controls.StackPanel __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			global::Microsoft.UI.Xaml.Controls.Grid.SetRow(__p1, 1);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 26, 8);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_9(global::Microsoft.UI.Xaml.Controls.Grid __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			global::Uno.Toolkit.UI.SafeArea.SetInsets(__p1, global::Uno.Toolkit.UI.SafeArea.InsetMask.VisibleBounds);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 19, 6);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_10(global::Microsoft.UI.Xaml.Controls.ScrollViewer __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 18, 4);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_11(global::Microsoft.UI.Xaml.Controls.Page __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			// Source ..\..\..\Presentation\MainPage.xaml (Line 1:2)
			
			// WARNING Property __p1.base does not exist on {http://schemas.microsoft.com/winfx/2006/xaml/presentation}Page, the namespace is http://www.w3.org/XML/1998/namespace. This error was considered irrelevant by the XamlFileGenerator
			__p1.NavigationCacheMode = global::Microsoft.UI.Xaml.Navigation.NavigationCacheMode.Required;
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_12(global::Microsoft.UI.Xaml.Controls.Page __p1, MainPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			/* _isTopLevelDictionary:False */
			__that._component_0 = __p1;
			// Class ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainPage
			global::Uno.UI.ResourceResolverSingleton.Instance.ApplyResource(__p1, global::Microsoft.UI.Xaml.Controls.Page.BackgroundProperty, "BackgroundBrush", isThemeResourceExtension: true, isHotReloadSupported: true, context: global::ImmutableEditableObjectAdapter.Samples.Uno.GlobalStaticResources.__ParseContext_);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 1, 2);
			__p1.CreationComplete();
		}
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		[global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdate]
		private class __MainPage_d7a1b33751a06f8c2b641494e8c25f72_ImmutableEditableObjectAdapterSamplesUnoPresentationMainPage
		{
			[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
			[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
			[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
			public class SC0
			{
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				private const string __baseUri_prefix_MainPage_d7a1b33751a06f8c2b641494e8c25f72 = "ms-appx:///";
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				private const string __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72 = "ms-appx:///Presentation/MainPage.xaml";
				global::Microsoft.UI.Xaml.NameScope __nameScope = new global::Microsoft.UI.Xaml.NameScope();
				global::System.Object __ResourceOwner_1;
				_View __rootInstance = null;
				public _View Build(object __ResourceOwner_1)
				{
					var __that = this;
					this.__ResourceOwner_1 = __ResourceOwner_1;
					this.__rootInstance = 
					new global::CommunityToolkit.WinUI.UI.Controls.DataGrid
					{
						IsParsing = true,
						// Source ..\..\..\Presentation\MainPage.xaml (Line 42:16)
					}
					.GenericApply(__that, __nameScope, (ApplyMethod_13))
					;
					if (__rootInstance is DependencyObject d)
					{
						if (global::Microsoft.UI.Xaml.NameScope.GetNameScope(d) == null)
						{
							global::Microsoft.UI.Xaml.NameScope.SetNameScope(d, __nameScope);
							__nameScope.Owner = d;
						}
						global::Uno.UI.FrameworkElementHelper.AddObjectReference(d, this);
					}
					return __rootInstance;
				}
				[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
				[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
				private void ApplyMethod_13(global::CommunityToolkit.WinUI.UI.Controls.DataGrid __p1, SC0 __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
				{
					__p1.SetBinding(
						global::CommunityToolkit.WinUI.UI.Controls.DataGrid.ItemsSourceProperty,
						new Microsoft.UI.Xaml.Data.Binding()
						{
							Path = @"Data",
							Mode = global::Microsoft.UI.Xaml.Data.BindingMode.TwoWay,
						}
					);
					global::Uno.Toolkit.UI.EditableExtensions.SetCommand(__p1, (global::System.Windows.Input.ICommand)((global::Microsoft.UI.Xaml.Markup.IMarkupExtensionOverrides)new global::Uno.Toolkit.UI.AncestorBindingExtension { Path = "DataContext.PersonChanged", AncestorType = typeof(global::Uno.Extensions.Reactive.UI.FeedView) }).ProvideValue(global::Uno.UI.Helpers.MarkupHelper.CreateParserContext(__p1, typeof(global::Uno.Toolkit.UI.EditableExtensions), "Command", typeof(global::System.Windows.Input.ICommand), (__ResourceOwner_1 as object as global::Uno.UI.IXamlResourceDictionaryProvider)?.GetResourceDictionary() ?? (object)__ResourceOwner_1)));
					global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_MainPage_d7a1b33751a06f8c2b641494e8c25f72, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/MainPage.xaml", 42, 16);
					__p1.CreationComplete();
				}
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				[global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdate]
				private class __MainPage_d7a1b33751a06f8c2b641494e8c25f72_ImmutableEditableObjectAdapterSamplesUno__ResourcesSC0_ImmutableEditableObjectAdapterSamplesUnoPresentationMainPage
				{
				}
			}
		}
		private global::Microsoft.UI.Xaml.Markup.ComponentHolder _component_0_Holder { get; } = new global::Microsoft.UI.Xaml.Markup.ComponentHolder(isWeak: true);
		private global::Microsoft.UI.Xaml.Controls.Page _component_0
		{
			get
			{
				return (global::Microsoft.UI.Xaml.Controls.Page)_component_0_Holder.Instance;
			}
			set
			{
				_component_0_Holder.Instance = value;
			}
		}
		private interface IMainPage_Bindings
		{
			void Initialize();
			void Update();
			void UpdateResources();
			void StopTracking();
			void NotifyXLoad(string name);
		}
		#pragma warning disable 0169 //  Suppress unused field warning in case Bindings is not used.
		private IMainPage_Bindings Bindings;
		#pragma warning restore 0169
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		private class MainPage_Bindings : IMainPage_Bindings
		{
			#if UNO_HAS_UIELEMENT_IMPLICIT_PINNING
			private global::System.WeakReference _ownerReference;
			private global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainPage Owner { get => (global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainPage)_ownerReference?.Target; set => _ownerReference = new global::System.WeakReference(value); }
			#else
			private global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainPage Owner { get; set; }
			#endif
			public MainPage_Bindings(global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.MainPage owner)
			{
				Owner = owner;
			}
			void IMainPage_Bindings.NotifyXLoad(string name)
			{
			}
			void IMainPage_Bindings.Initialize()
			{
			}
			void IMainPage_Bindings.Update()
			{
				var owner = Owner;
			}
			void IMainPage_Bindings.UpdateResources()
			{
				var owner = Owner;
				owner._component_0.UpdateResourceBindings();
			}
			void IMainPage_Bindings.StopTracking()
			{
				var owner = Owner;
			}
		}
	}
}
