// <autogenerated />
#pragma warning disable 618 // Ignore obsolete members warnings
#pragma warning disable 105 // Ignore duplicate namespaces
#pragma warning disable 1591 // Ignore missing XML comment warnings
#pragma warning disable CS8669 // Ignore annotation for nullable reference types
#pragma warning disable CS9113 // Parameter is unread
#pragma warning disable CS0114
#pragma warning disable CS0108
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Uno.UI;
using Uno.UI.Xaml;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Documents;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Media.Animation;
using Microsoft.UI.Xaml.Shapes;
using Windows.UI.Text;
using Uno.Extensions;
using Uno;
using Uno.UI.Helpers;
using Uno.UI.Helpers.Xaml;
using ImmutableEditableObjectAdapter.Samples.Uno;

#if HAS_UNO_SKIA
using _View = Microsoft.UI.Xaml.UIElement;
#elif __ANDROID__
using _View = Android.Views.View;
#elif __APPLE_UIKIT__ || __IOS__ || __TVOS__
using _View = UIKit.UIView;
#else
using _View = Microsoft.UI.Xaml.UIElement;
#endif

namespace ImmutableEditableObjectAdapter.Samples.Uno.Presentation
{
	partial class SecondPage : global::Microsoft.UI.Xaml.Controls.Page
	{
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private const string __baseUri_prefix_SecondPage_43d52a7b8ef7245df955f57a30f3e88c = "ms-appx:///";
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private const string __baseUri_SecondPage_43d52a7b8ef7245df955f57a30f3e88c = "ms-appx:///Presentation/SecondPage.xaml";
		private global::Microsoft.UI.Xaml.NameScope __nameScope = new global::Microsoft.UI.Xaml.NameScope();
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void InitializeComponent()
		{
			NameScope.SetNameScope(this, __nameScope);
			var __that = this;
			base.IsParsing = true;
			// Source ..\..\..\Presentation\SecondPage.xaml (Line 1:2)
			base.Content = 
			new global::Microsoft.UI.Xaml.Controls.Grid
			{
				IsParsing = true,
				RowDefinitions = 
				{
					new global::Microsoft.UI.Xaml.Controls.RowDefinition
					{
						Height = new global::Microsoft.UI.Xaml.GridLength(1f, global::Microsoft.UI.Xaml.GridUnitType.Auto),
						// Source ..\..\..\Presentation\SecondPage.xaml (Line 14:8)
					}
					,
					new global::Microsoft.UI.Xaml.Controls.RowDefinition
					{
						// Source ..\..\..\Presentation\SecondPage.xaml (Line 15:8)
					}
					,
				}
				,
				// Source ..\..\..\Presentation\SecondPage.xaml (Line 12:4)
				Children = 
				{
					new global::Uno.Toolkit.UI.NavigationBar
					{
						IsParsing = true,
						Content = @"Second Page",
						// Source ..\..\..\Presentation\SecondPage.xaml (Line 17:6)
					}
					.GenericApply(__that, __nameScope, (ApplyMethod_1))
					,
					new global::Microsoft.UI.Xaml.Controls.StackPanel
					{
						IsParsing = true,
						HorizontalAlignment = global::Microsoft.UI.Xaml.HorizontalAlignment.Center,
						VerticalAlignment = global::Microsoft.UI.Xaml.VerticalAlignment.Center,
						// Source ..\..\..\Presentation\SecondPage.xaml (Line 18:6)
						Children = 
						{
							new global::Microsoft.UI.Xaml.Controls.TextBlock
							{
								IsParsing = true,
								HorizontalAlignment = global::Microsoft.UI.Xaml.HorizontalAlignment.Center,
								VerticalAlignment = global::Microsoft.UI.Xaml.VerticalAlignment.Center,
								Margin = new global::Microsoft.UI.Xaml.Thickness(8),
								// Source ..\..\..\Presentation\SecondPage.xaml (Line 21:8)
							}
							.GenericApply(__that, __nameScope, (ApplyMethod_2))
							,
						}
					}
					.GenericApply(__that, __nameScope, (ApplyMethod_3))
					,
				}
			}
			.GenericApply(__that, __nameScope, (ApplyMethod_4))
			;
			
			this
			.GenericApply(__that, __nameScope, (ApplyMethod_5))
			.GenericApply(__that, __nameScope, (ApplyMethod_6))
			;
			OnInitializeCompleted();

			Bindings = new SecondPage_Bindings(this);
			((global::Microsoft.UI.Xaml.FrameworkElement)this).Loading += __UpdateBindingsAndResources;
		}
		partial void OnInitializeCompleted();
		private void __UpdateBindingsAndResources(global::Microsoft.UI.Xaml.FrameworkElement s, object e)
		{
			this.Bindings.UpdateResources();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_1(global::Uno.Toolkit.UI.NavigationBar __p1, SecondPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_SecondPage_43d52a7b8ef7245df955f57a30f3e88c, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/SecondPage.xaml", 17, 6);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_2(global::Microsoft.UI.Xaml.Controls.TextBlock __p1, SecondPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			__p1.SetBinding(
				global::Microsoft.UI.Xaml.Controls.TextBlock.TextProperty,
				new Microsoft.UI.Xaml.Data.Binding()
				{
					Path = @"Entity.Name",
				}
			);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_SecondPage_43d52a7b8ef7245df955f57a30f3e88c, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/SecondPage.xaml", 21, 8);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_3(global::Microsoft.UI.Xaml.Controls.StackPanel __p1, SecondPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			global::Microsoft.UI.Xaml.Controls.Grid.SetRow(__p1, 1);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_SecondPage_43d52a7b8ef7245df955f57a30f3e88c, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/SecondPage.xaml", 18, 6);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_4(global::Microsoft.UI.Xaml.Controls.Grid __p1, SecondPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			global::Uno.Toolkit.UI.SafeArea.SetInsets(__p1, global::Uno.Toolkit.UI.SafeArea.InsetMask.VisibleBounds);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_SecondPage_43d52a7b8ef7245df955f57a30f3e88c, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/SecondPage.xaml", 12, 4);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_5(global::Microsoft.UI.Xaml.Controls.Page __p1, SecondPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			// Source ..\..\..\Presentation\SecondPage.xaml (Line 1:2)
			
			// WARNING Property __p1.base does not exist on {http://schemas.microsoft.com/winfx/2006/xaml/presentation}Page, the namespace is http://www.w3.org/XML/1998/namespace. This error was considered irrelevant by the XamlFileGenerator
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_6(global::Microsoft.UI.Xaml.Controls.Page __p1, SecondPage __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			/* _isTopLevelDictionary:False */
			__that._component_0 = __p1;
			// Class ImmutableEditableObjectAdapter.Samples.Uno.Presentation.SecondPage
			global::Uno.UI.ResourceResolverSingleton.Instance.ApplyResource(__p1, global::Microsoft.UI.Xaml.Controls.Page.BackgroundProperty, "BackgroundBrush", isThemeResourceExtension: true, isHotReloadSupported: true, context: global::ImmutableEditableObjectAdapter.Samples.Uno.GlobalStaticResources.__ParseContext_);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_SecondPage_43d52a7b8ef7245df955f57a30f3e88c, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/SecondPage.xaml", 1, 2);
			__p1.CreationComplete();
		}
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		[global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdate]
		private class __SecondPage_43d52a7b8ef7245df955f57a30f3e88c_ImmutableEditableObjectAdapterSamplesUnoPresentationSecondPage
		{
		}
		private global::Microsoft.UI.Xaml.Markup.ComponentHolder _component_0_Holder { get; } = new global::Microsoft.UI.Xaml.Markup.ComponentHolder(isWeak: true);
		private global::Microsoft.UI.Xaml.Controls.Page _component_0
		{
			get
			{
				return (global::Microsoft.UI.Xaml.Controls.Page)_component_0_Holder.Instance;
			}
			set
			{
				_component_0_Holder.Instance = value;
			}
		}
		private interface ISecondPage_Bindings
		{
			void Initialize();
			void Update();
			void UpdateResources();
			void StopTracking();
			void NotifyXLoad(string name);
		}
		#pragma warning disable 0169 //  Suppress unused field warning in case Bindings is not used.
		private ISecondPage_Bindings Bindings;
		#pragma warning restore 0169
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		private class SecondPage_Bindings : ISecondPage_Bindings
		{
			#if UNO_HAS_UIELEMENT_IMPLICIT_PINNING
			private global::System.WeakReference _ownerReference;
			private global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.SecondPage Owner { get => (global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.SecondPage)_ownerReference?.Target; set => _ownerReference = new global::System.WeakReference(value); }
			#else
			private global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.SecondPage Owner { get; set; }
			#endif
			public SecondPage_Bindings(global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.SecondPage owner)
			{
				Owner = owner;
			}
			void ISecondPage_Bindings.NotifyXLoad(string name)
			{
			}
			void ISecondPage_Bindings.Initialize()
			{
			}
			void ISecondPage_Bindings.Update()
			{
				var owner = Owner;
			}
			void ISecondPage_Bindings.UpdateResources()
			{
				var owner = Owner;
				owner._component_0.UpdateResourceBindings();
			}
			void ISecondPage_Bindings.StopTracking()
			{
				var owner = Owner;
			}
		}
	}
}
