// <autogenerated />
#pragma warning disable 618 // Ignore obsolete members warnings
#pragma warning disable 105 // Ignore duplicate namespaces
#pragma warning disable 1591 // Ignore missing XML comment warnings
#pragma warning disable CS8669 // Ignore annotation for nullable reference types
#pragma warning disable CS9113 // Parameter is unread
#pragma warning disable CS0114
#pragma warning disable CS0108
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Uno.UI;
using Uno.UI.Xaml;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Documents;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Media.Animation;
using Microsoft.UI.Xaml.Shapes;
using Windows.UI.Text;
using Uno.Extensions;
using Uno;
using Uno.UI.Helpers;
using Uno.UI.Helpers.Xaml;
using ImmutableEditableObjectAdapter.Samples.Uno;

#if HAS_UNO_SKIA
using _View = Microsoft.UI.Xaml.UIElement;
#elif __ANDROID__
using _View = Android.Views.View;
#elif __APPLE_UIKIT__ || __IOS__ || __TVOS__
using _View = UIKit.UIView;
#else
using _View = Microsoft.UI.Xaml.UIElement;
#endif

namespace ImmutableEditableObjectAdapter.Samples.Uno.Presentation
{
	partial class Shell : global::Microsoft.UI.Xaml.Controls.UserControl
	{
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private const string __baseUri_prefix_Shell_06fa6f052ecac338a77d04463cc3e67a = "ms-appx:///";
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private const string __baseUri_Shell_06fa6f052ecac338a77d04463cc3e67a = "ms-appx:///Presentation/Shell.xaml";
		private global::Microsoft.UI.Xaml.NameScope __nameScope = new global::Microsoft.UI.Xaml.NameScope();
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void InitializeComponent()
		{
			NameScope.SetNameScope(this, __nameScope);
			var __that = this;
			base.IsParsing = true;
			// Source ..\..\..\Presentation\Shell.xaml (Line 1:2)
			base.Content = 
			new global::Microsoft.UI.Xaml.Controls.Border
			{
				IsParsing = true,
				// Source ..\..\..\Presentation\Shell.xaml (Line 11:4)
				Child = 
				new global::Uno.Toolkit.UI.ExtendedSplashScreen
				{
					IsParsing = true,
					Name = "Splash",
					HorizontalAlignment = global::Microsoft.UI.Xaml.HorizontalAlignment.Stretch,
					VerticalAlignment = global::Microsoft.UI.Xaml.VerticalAlignment.Stretch,
					HorizontalContentAlignment = global::Microsoft.UI.Xaml.HorizontalAlignment.Stretch,
					VerticalContentAlignment = global::Microsoft.UI.Xaml.VerticalAlignment.Stretch,
					LoadingContentTemplate = 					new global::Microsoft.UI.Xaml.DataTemplate(this, (__owner) => 					new __Shell_06fa6f052ecac338a77d04463cc3e67a_ImmutableEditableObjectAdapterSamplesUnoPresentationShell.SC0().Build(__owner)
					)					.GenericApply(__that, __nameScope, (ApplyMethod_0))
					,
					// Source ..\..\..\Presentation\Shell.xaml (Line 12:6)
				}
				.GenericApply(__that, __nameScope, (ApplyMethod_1))
			}
			.GenericApply(__that, __nameScope, (ApplyMethod_2))
			;
			
			this
			.GenericApply(__that, __nameScope, (ApplyMethod_3))
			.GenericApply(__that, __nameScope, (ApplyMethod_4))
			;
			OnInitializeCompleted();

			Bindings = new Shell_Bindings(this);
			((global::Microsoft.UI.Xaml.FrameworkElement)this).Loading += __UpdateBindingsAndResources;
		}
		partial void OnInitializeCompleted();
		private void __UpdateBindingsAndResources(global::Microsoft.UI.Xaml.FrameworkElement s, object e)
		{
			this.Bindings.UpdateResources();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_0(global::System.Object __p1, Shell __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			global::Uno.UI.Helpers.MarkupHelper.SetElementProperty(__p1, "OriginalSourceLocation", "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/Shell.xaml#L18:10");
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_1(global::Uno.Toolkit.UI.ExtendedSplashScreen __p1, Shell __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			__nameScope.RegisterName("Splash", __p1);
			__that.Splash = __p1;
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_Shell_06fa6f052ecac338a77d04463cc3e67a, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/Shell.xaml", 12, 6);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_2(global::Microsoft.UI.Xaml.Controls.Border __p1, Shell __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			/* _isTopLevelDictionary:False */
			__that._component_0 = __p1;
			global::Uno.UI.ResourceResolverSingleton.Instance.ApplyResource(__p1, global::Microsoft.UI.Xaml.Controls.Border.BackgroundProperty, "BackgroundBrush", isThemeResourceExtension: true, isHotReloadSupported: true, context: global::ImmutableEditableObjectAdapter.Samples.Uno.GlobalStaticResources.__ParseContext_);
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_Shell_06fa6f052ecac338a77d04463cc3e67a, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/Shell.xaml", 11, 4);
			__p1.CreationComplete();
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_3(global::Microsoft.UI.Xaml.Controls.UserControl __p1, Shell __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			// Source ..\..\..\Presentation\Shell.xaml (Line 1:2)
			
			// WARNING Property __p1.base does not exist on {http://schemas.microsoft.com/winfx/2006/xaml/presentation}UserControl, the namespace is http://www.w3.org/XML/1998/namespace. This error was considered irrelevant by the XamlFileGenerator
		}
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		private void ApplyMethod_4(global::Microsoft.UI.Xaml.Controls.UserControl __p1, Shell __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
		{
			// Class ImmutableEditableObjectAdapter.Samples.Uno.Presentation.Shell
			global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_Shell_06fa6f052ecac338a77d04463cc3e67a, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/Shell.xaml", 1, 2);
			__p1.CreationComplete();
		}
		private global::Microsoft.UI.Xaml.Data.ElementNameSubject _SplashSubject { get; set; } = new global::Microsoft.UI.Xaml.Data.ElementNameSubject();
		private global::Uno.Toolkit.UI.ExtendedSplashScreen Splash
		{
			get
			{
				return (global::Uno.Toolkit.UI.ExtendedSplashScreen)_SplashSubject.ElementInstance;
			}
			set
			{
				_SplashSubject.ElementInstance = value;
			}
		}
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		[global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdate]
		private class __Shell_06fa6f052ecac338a77d04463cc3e67a_ImmutableEditableObjectAdapterSamplesUnoPresentationShell
		{
			[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
			[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
			[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
			public class SC0
			{
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				private const string __baseUri_prefix_Shell_06fa6f052ecac338a77d04463cc3e67a = "ms-appx:///";
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				private const string __baseUri_Shell_06fa6f052ecac338a77d04463cc3e67a = "ms-appx:///Presentation/Shell.xaml";
				global::Microsoft.UI.Xaml.NameScope __nameScope = new global::Microsoft.UI.Xaml.NameScope();
				global::System.Object __ResourceOwner_1;
				_View __rootInstance = null;
				public _View Build(object __ResourceOwner_1)
				{
					var __that = this;
					this.__ResourceOwner_1 = __ResourceOwner_1;
					this.__rootInstance = 
					new global::Microsoft.UI.Xaml.Controls.Grid
					{
						IsParsing = true,
						RowDefinitions = 
						{
							new global::Microsoft.UI.Xaml.Controls.RowDefinition
							{
								Height = new global::Microsoft.UI.Xaml.GridLength(2f, global::Microsoft.UI.Xaml.GridUnitType.Star),
								// Source ..\..\..\Presentation\Shell.xaml (Line 21:16)
							}
							,
							new global::Microsoft.UI.Xaml.Controls.RowDefinition
							{
								// Source ..\..\..\Presentation\Shell.xaml (Line 22:16)
							}
							,
						}
						,
						// Source ..\..\..\Presentation\Shell.xaml (Line 19:12)
						Children = 
						{
							new global::Microsoft.UI.Xaml.Controls.ProgressRing
							{
								IsParsing = true,
								IsActive = true,
								VerticalAlignment = global::Microsoft.UI.Xaml.VerticalAlignment.Center,
								HorizontalAlignment = global::Microsoft.UI.Xaml.HorizontalAlignment.Center,
								Height = 100f,
								Width = 100f,
								// Source ..\..\..\Presentation\Shell.xaml (Line 25:14)
							}
							.GenericApply(__that, __nameScope, (ApplyMethod_6))
							,
						}
					}
					.GenericApply(__that, __nameScope, (ApplyMethod_7))
					;
					if (__rootInstance is DependencyObject d)
					{
						if (global::Microsoft.UI.Xaml.NameScope.GetNameScope(d) == null)
						{
							global::Microsoft.UI.Xaml.NameScope.SetNameScope(d, __nameScope);
							__nameScope.Owner = d;
						}
						global::Uno.UI.FrameworkElementHelper.AddObjectReference(d, this);
					}
					return __rootInstance;
				}
				[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
				[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
				private void ApplyMethod_6(global::Microsoft.UI.Xaml.Controls.ProgressRing __p1, SC0 __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
				{
					global::Microsoft.UI.Xaml.Controls.Grid.SetRow(__p1, 1);
					global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_Shell_06fa6f052ecac338a77d04463cc3e67a, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/Shell.xaml", 25, 14);
					__p1.CreationComplete();
				}
				[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
				[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
				private void ApplyMethod_7(global::Microsoft.UI.Xaml.Controls.Grid __p1, SC0 __that, global::Microsoft.UI.Xaml.NameScope __nameScope)
				{
					global::Uno.UI.FrameworkElementHelper.SetBaseUri(__p1, __baseUri_Shell_06fa6f052ecac338a77d04463cc3e67a, "file:///C:/Users/rca/Documents/cs/ImmutableEditableObjectAdapter/sample/ImmutableEditableObjectAdapter.Samples.Uno/ImmutableEditableObjectAdapter.Samples.Uno/Presentation/Shell.xaml", 19, 12);
					__p1.CreationComplete();
				}
				[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
				[global::System.Runtime.CompilerServices.CreateNewOnMetadataUpdate]
				private class __Shell_06fa6f052ecac338a77d04463cc3e67a_ImmutableEditableObjectAdapterSamplesUno__ResourcesSC0_ImmutableEditableObjectAdapterSamplesUnoPresentationShell
				{
				}
			}
		}
		private global::Microsoft.UI.Xaml.Markup.ComponentHolder _component_0_Holder { get; } = new global::Microsoft.UI.Xaml.Markup.ComponentHolder(isWeak: true);
		private global::Microsoft.UI.Xaml.Controls.Border _component_0
		{
			get
			{
				return (global::Microsoft.UI.Xaml.Controls.Border)_component_0_Holder.Instance;
			}
			set
			{
				_component_0_Holder.Instance = value;
			}
		}
		private interface IShell_Bindings
		{
			void Initialize();
			void Update();
			void UpdateResources();
			void StopTracking();
			void NotifyXLoad(string name);
		}
		#pragma warning disable 0169 //  Suppress unused field warning in case Bindings is not used.
		private IShell_Bindings Bindings;
		#pragma warning restore 0169
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Generated code")]
		[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2111", Justification = "Generated code")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		private class Shell_Bindings : IShell_Bindings
		{
			#if UNO_HAS_UIELEMENT_IMPLICIT_PINNING
			private global::System.WeakReference _ownerReference;
			private global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.Shell Owner { get => (global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.Shell)_ownerReference?.Target; set => _ownerReference = new global::System.WeakReference(value); }
			#else
			private global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.Shell Owner { get; set; }
			#endif
			public Shell_Bindings(global::ImmutableEditableObjectAdapter.Samples.Uno.Presentation.Shell owner)
			{
				Owner = owner;
			}
			void IShell_Bindings.NotifyXLoad(string name)
			{
			}
			void IShell_Bindings.Initialize()
			{
			}
			void IShell_Bindings.Update()
			{
				var owner = Owner;
			}
			void IShell_Bindings.UpdateResources()
			{
				var owner = Owner;
				owner._component_0.UpdateResourceBindings();
			}
			void IShell_Bindings.StopTracking()
			{
				var owner = Owner;
			}
		}
	}
}
