//----------------------
			// <auto-generated>
			//	Generated by the ForceBindingsUpdateGenTool_1 v1. DO NOT EDIT!
			//	Manual changes to this file will be overwritten if the code is regenerated.
			// </auto-generated>
			//----------------------
			#pragma warning disable

			namespace ImmutableEditableObjectAdapter.Samples.Uno.Presentation
			{

partial class MainPage : global::Uno.Extensions.Navigation.IForceBindingsUpdate
				{

					ValueTask global::Uno.Extensions.Navigation.IForceBindingsUpdate.ForceBindingsUpdateAsync()
					{
						if(this.Bindings is not null)
						{
							this.Bindings.Update();
						}
						return ValueTask.CompletedTask;
					}

				}
			}