// <auto-generated>
namespace ImmutableEditableObjectAdapter.Samples.Uno.Presentation
{
	partial class Shell
	{
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		private static global::Uno.UI.Xaml.RoutedEventFlag __uno_ImplementedRoutedEvents = global::Uno.UI.Xaml.UIElementGeneratedProxy.RegisterImplementedRoutedEvents(
			typeof(Shell),
			global::Uno.UI.Xaml.RoutedEventFlag.None
		);
	}
}
